# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='is_seen_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
